create table if not exists public.craft_apps (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  display_name text not null,
  repo_owner text not null default 'storytold',
  repo_name text not null,
  default_branch text not null default 'main',
  installed_version text,
  latest_release_tag text,
  latest_release_url text,
  latest_release_published_at timestamptz,
  latest_commit_sha text,
  latest_commit_url text,
  latest_commit_message text,
  latest_commit_at timestamptz,
  last_checked_at timestamptz,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crawl_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running','success','partial','failed')),
  apps_checked integer not null default 0,
  changes_found integer not null default 0,
  error_count integer not null default 0,
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.update_events (
  id bigint generated by default as identity primary key,
  app_id bigint not null references public.craft_apps(id) on delete cascade,
  crawl_run_id bigint references public.crawl_runs(id) on delete set null,
  event_type text not null check (event_type in ('release','commit')),
  old_value text,
  new_value text not null,
  title text,
  url text,
  metadata jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now(),
  unique (app_id, event_type, new_value)
);

create index if not exists craft_apps_enabled_idx
  on public.craft_apps(enabled);

create index if not exists update_events_app_detected_idx
  on public.update_events(app_id, detected_at desc);

create index if not exists crawl_runs_started_idx
  on public.crawl_runs(started_at desc);

alter table public.craft_apps enable row level security;
alter table public.crawl_runs enable row level security;
alter table public.update_events enable row level security;

revoke all on table public.craft_apps from anon, authenticated;
revoke all on table public.crawl_runs from anon, authenticated;
revoke all on table public.update_events from anon, authenticated;

insert into public.craft_apps (slug, display_name, repo_name)
values
  ('designcraft','DesignCraft','designcraft'),
  ('effectcraft','EffectCraft','effectcraft'),
  ('filmcraft','FilmCraft','filmcraft'),
  ('lightcraft','LightCraft','lightcraft'),
  ('pdfcraft','PdfCraft','pdfcraft'),
  ('photocraft','PhotoCraft','photocraft'),
  ('vectorcraft','VectorCraft','vectorcraft')
on conflict (slug) do update
set
  display_name = excluded.display_name,
  repo_name = excluded.repo_name,
  updated_at = now();

comment on table public.craft_apps is
  'Remote ArtCraft watcher configuration and last-seen upstream state.';

comment on table public.crawl_runs is
  'Execution history for the remote GitHub crawler.';

comment on table public.update_events is
  'Deduplicated release and commit changes detected for watched ArtCraft apps.';
